// See https://aka.ms/new-console-template for more information
Console.WriteLine("letra da musica É sal");
Console.WriteLine("Na-na-na-na-na");
Console.WriteLine("Na-na-na-ahn, na-na-na-na");
Console.WriteLine("Na-na-na-ahn, na-na-na-na");
Console.WriteLine("Na-na-na-ahn, na-na-na-na");
Console.WriteLine("Pivete, é sal");
Console.WriteLine("Óia as cumade passando mal, que legal");
Console.WriteLine("Hoje tem, já acionei o canal");
Console.WriteLine("Tá nevando em Fortal, já resgata o Manaus");
Console.WriteLine("Mas vai pela sombra");
Console.WriteLine("Quem tá andando com Deus nunca se assombra");
Console.WriteLine("Os home' tão na esquina, cortando a lombra");
Console.WriteLine("Peugeotzin' no Titanzin' vai cortando a onda");
Console.WriteLine("Nunca vi mais grande");
Console.WriteLine("Quadrada na beca de veludo");
Console.WriteLine("Ninguém sabia, eu quero todo mundo mudo");
Console.WriteLine("Vai botando a fé no submundo");
Console.WriteLine("Tal hora tu vai acabar tomando um susto");
Console.WriteLine("Olha o caminhar do elemento");
Console.WriteLine("É o passo bem lento, vai fechando o tempo");
Console.WriteLine("Canhão, faca na cintura");
Console.WriteLine("Disposição pra tombar duas viatura");
Console.WriteLine("Fortal City é uma mistura");
Console.WriteLine("Morando na praia e mesmo assim a vida é dura (oah)");
Console.WriteLine("Tá geral suave, do nada o clima muda (oah)");
Console.WriteLine("Vai passar na frente, a máquina te costura (oah)");
Console.WriteLine("Ela te costura (tra, tra, tra)");
Console.WriteLine("Quadrada na beca de veludo");
Console.WriteLine("Ninguém sabia, eu quero todo mundo mudo");
Console.WriteLine("Vai botando a fé no submundo");
Console.WriteLine("Tal hora tu vai acabar tomando um susto");
Console.WriteLine("Tu vai acabar tomando um susto");
Console.WriteLine("Então se adianta, tu tá interado");
Console.WriteLine("Que o nego é considerado");
Console.WriteLine("E anda com vários do seu lado");
Console.WriteLine("Da Oeste pra Zona Sul, é o terror do Pirambu");
Console.WriteLine("Veio pra arrastar todo mundo");
Console.WriteLine("É ele que faz a feira, que traz o cera");
Console.WriteLine("É o brinca, é a bagaceira, tu que é o besta");
Console.WriteLine("É a nata, muita experiência, dez anos de caminhada");
Console.WriteLine("Tá sempre se arriscando na missão, mas nunca deu falha");
Console.WriteLine("Trago essa quadrada na beca de veludo");
Console.WriteLine("Ninguém sabia, eu quero todo mundo mudo");
Console.WriteLine("Vai botando a fé no submundo");
Console.WriteLine("Tal hora tu vai acabar tomando um susto");
Console.WriteLine("Tu vai acabar tomando um susto");